// <auto-generated />
namespace Musicalog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_tablealbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tablealbum));
        
        string IMigrationMetadata.Id
        {
            get { return "202011050137402_create_table-album"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
